### ISSUE TITLE
investigate removing `scipy` dependency

### ISSUE THREAD

**Issue by tomsilver** [Learning-and-Intelligent-Systems/predicators#1083]
it's a pain to install (slow in general, and many steps on fresh ubuntu images) and we're barely using it right now

**Comment by tomsilver** [comment]
the main usage is in behavior -- let's revisit this after refactoring behavior stuff

**Comment by ronuchit** [comment]
turns out we can't do this because sklearn depends on scipy anyway, even if we were to remove the direct scipy dependencies in our codebase. closing for now
