### ISSUE TITLE
better handle lowercase boolean values in command line overrides

### ISSUE THREAD

**Issue by tomsilver** [Learning-and-Intelligent-Systems/predicators#1084]
right now if someone does `--foo false`, then that gets evaluated to the string `"false"`, and `bool("false")` is True. @Alchemy5 ran into this the hard way, sorry @Alchemy5 !

for discussion: should we treat `false` as `False`, or raise an error, or what?

@ronuchit

**Comment by ronuchit** [comment]
just change https://github.com/Learning-and-Intelligent-Systems/predicators/blob/master/src/utils.py#L2483
to `in ("False", "false")`

@Alchemy5 feel free to open a PR contributing this change, if you do, make sure to update https://github.com/Learning-and-Intelligent-Systems/predicators/blob/master/tests/test_utils.py#L2848 too

**Comment by tomsilver** [comment]
Varun's time with us is very short, so I'll take care of this
