### ISSUE TITLE
add fast downward integration

### ISSUE THREAD

**Issue by tomsilver** [Learning-and-Intelligent-Systems/predicators#1108]
for PDDL-only domains, we want to be able to compare to FD. also may be useful in other cases.

**Comment by ronuchit** [comment]
we should discuss the design, in light of the fact that we already have `fast_downward_translator` in `third_party`. maybe we just want to add `fast_downward_search` and manually run translator then search? then we'd want to refactor `utils.all_ground_nsrts_fd_translator` to expose the `sas_task` which needs to be written out to a file, then call search on it

**Comment by tomsilver** [comment]
you're more familiar with the inner workings of FD than I am, but that sounds reasonable to me
