### ISSUE TITLE
fix fast downward output parsing to use correct keywords

### ISSUE THREAD

**Issue by tomsilver** [Learning-and-Intelligent-Systems/predicators#1172]
https://github.com/Learning-and-Intelligent-Systems/predicators/blob/master/src/planning.py#L793

currently we're using "Evaluated" where we should be using "Expanded". I believe we want to use "Evaluated" instead of "Generated" too.

but @ronuchit lmk if you have more information

**Comment by ronuchit** [comment]
you'll have to play around with it, i'm not sure
