### ISSUE TITLE
fix pybullet cover regression

### ISSUE THREAD

**Issue by tomsilver** [Learning-and-Intelligent-Systems/predicators#1182]
see discussion in #1174

**Comment by williamshen-nz** [comment]
Latest pybullet changes seems to have dropped coverage on cover again: https://github.com/Learning-and-Intelligent-Systems/predicators/commit/79ec87b98236d49e9bc59e82a0da4266a22c447e

```
Git commit hashes seen in results/:
810afd7a473be17fbe7ab92f5065a1ce8d84a1f2


AGGREGATED DATA OVER SEEDS:
                       NUM_TRAIN_TASKS    NUM_SOLVED AVG_NUM_PREDS AVG_TEST_TIME  AVG_NODES_CREATED LEARNING_TIME  NUM_SEEDS
EXPERIMENT_ID                                                                                                               
pybullet_blocks-oracle    50.00 (0.00)  47.18 (1.61)   5.00 (0.00)   0.35 (0.10)  3530.42 (1867.35)   0.00 (0.00)        100
pybullet_cover-oracle     50.00 (0.00)  43.41 (2.31)   5.00 (0.00)   0.07 (0.01)        6.69 (0.40)   0.00 (0.00)        100
```

**Comment by williamshen-nz** [comment]
We can disregard all the IKFast and Panda-specific stuff, as fetch doesn't use it.

In `pybullet_covers.py`

```
    _move_to_pose_tol: ClassVar[float] = 1e-4
```

Pose tolerance was relaxed so it should only do better, if anything. Not sure what's happening, will rerun supercloud job and see if it's consistent.

**Comment by tomsilver** [comment]
it is possible that the `_move_to_pose_tol` relaxation hurts performance. that parameter affects the controller, not the physics

**Comment by williamshen-nz** [comment]
Yes, I see what you mean. I remember I changed it from the default as it didn't work otherwise.

Will experiment and run some regression tests

**Comment by tomsilver** [comment]
I looked at this a little and it does seem like the `_move_to_pose_tol` change was responsible for the regression. We could make that hyperparameter robot-specific, but I think it's fine to just swallow the slight regression. Closing this for now.
