### ISSUE TITLE
Real Panda Execution

### ISSUE THREAD

**Issue by williamshen-nz** [Learning-and-Intelligent-Systems/predicators#1218]
Just an issue to track todos for that so I can remember:

- [x] Move Panda in simulation to world origin (not completely necessary, just need table to be basically the same height as the robot)
- [x] LISDF Plan Executor server: https://github.com/williamshen-nz/panda-robot-server
- [x] Expose a panda client to predicators: https://github.com/williamshen-nz/panda-robot-client
- [x] Perception - determine best camera setup, probably need opencv if we just use aruco markers

**Comment by williamshen-nz** [comment]
Panda Server and Client are implemented and working on the real robot. The server will also respect the duration in the commands of a LISDF Plan so we don't have to wait for it to take 2 minutes to go home.

So it seems like perception is the next thing to do, apart from making sure the plans we generate can be reliably executed.

**Comment by williamshen-nz** [comment]
**Immediate next steps:**

- [ ] Recalibrate extrinsics of the two inward-facing cameras (to the robot)
- [ ] Capture multiple scenarios of the blocks, RGB + D
- [ ] Dump intrinsics, extrinsics and RGB-Ds into a folder
- [ ] Handover to Tom

Depending on how we want to process the images, we could use something like open3d (might be overkill) or just write our own methods.

**Comment by tomsilver** [comment]
@williamshen-nz I guess we can close this?

**Comment by williamshen-nz** [comment]
Yep! Will close
