### ISSUE TITLE
Update setup.py to enable cuda PyTorch

### ISSUE THREAD

**Issue by lilianluong** [Learning-and-Intelligent-Systems/predicators#1405]
The current PyTorch version being installed is cpu-only.

Locally, running `conda remove pytorch` followed by `conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia` (from https://pytorch.org/get-started/locally/) seemed to work for my needs, but we might want to update `setup.py` accordingly.

Motivation: be able to train ML models using GPU.

**Comment by lilianluong** [comment]
Also had to set an environment variable to still enable `torch.use_deterministic_algorithms(mode=True)`.

From https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility:
`export CUBLAS_WORKSPACE_CONFIG=:4096:8`

**Comment by tomsilver** [comment]
after further thought and discussion, we decided to leave setup.py alone, but to raise a helpful error if someone is attempting to use a GPU but doesn't have the right version of pytorch installed. the main reason is that the pytorch dependency varies per system
