### ISSUE TITLE
investigate painting  + grammar search with everything except goal predicates ablated

### ISSUE THREAD

**Issue by tomsilver** [Learning-and-Intelligent-Systems/predicators#161]

**Comment by ronuchit** [comment]
Is there a reason holdingside/holdingtop can't be ablated?

**Comment by tomsilver** [comment]
It would just require a grammar update (as of when I wrote the issue) because they're binary. I'm not sure if the updates I made to do clear would work here... maybe

**Comment by ronuchit** [comment]
Actually, can't holdingside/top in the painting env only be functions of the robot? We already know from the holding predicate that an object is held, and so we just need to test whether the robot's grasp is top or side in the holdingside/top test. If you agree with this, I can update the env itself?

**Comment by tomsilver** [comment]
Sure, sounds good.

**Comment by ronuchit** [comment]
fixed in #164 and updated issue description

**Comment by ronuchit** [comment]
This is being addressed by the most recent series of PRs (#231, #232, #233) and is the main point of investigation right now. Will close this PR.
