### ISSUE TITLE
Installation Issues with newer Python versions

### ISSUE THREAD

**Issue by yichao-liang** [Learning-and-Intelligent-Systems/predicators#1620]
The [installation guide](https://github.com/Learning-and-Intelligent-Systems/predicators#installation) suggests the repo works with Python 3.8+ but I encountered incompatibility errors in installing the dependencies when using Python 3.12.2. 

So maybe a more specific guide would be helpful?

Thanks,
Yichao

**Comment by NishanthJKumar** [comment]
Good point; a UROP of mine had a similar problem recently. I think it works for versions 3.8 - 3.11. Should we update the README accordingly @tomsilver ?

**Comment by tomsilver** [comment]
Yes please do, thanks!

**Comment by NishanthJKumar** [comment]
addressed by #1630
