### ISSUE TITLE
StickButtonEnv issues

### ISSUE THREAD

**Issue by ashayathalye** [Learning-and-Intelligent-Systems/predicators#1626]
- operator RobotPressButton (and its option) has a stick as an argument, but the stick is never used or referenced by anything, so it seems unnecessary
- operators RobotMoveToButtonFromNothing and RobotMoveToButtonFromButton don't have stick as an argument, but access the state of the stick inside the evaluation of the predicate HandEmpty
- "press" action dimension affects both pressing a button, and placing a stick. This is can cause unintended behavior when a button and holder are both under the stick, in which case the stick is dropped into the holder when only the button was meant to be pressed (e.g. when executing option StickPressButton). The press and place action dimensions should be different.
- PlaceStick option accesses holder state but does not have it as an option argument. 

solution:
- should be able to remove stick as an argument from RobotPressButton without issue
- should introduce an attribute "grip" or something like that to the robot, and then calculate HandEmpty that way
- add action dimension for place, separate from press
- add holder object as parameter to the PlaceStick option and corresponding nsrt

**Comment by yichao-liang** [comment]
I agree with the first point. It seems like it's only introduced in the [latest merge](https://github.com/Learning-and-Intelligent-Systems/predicators/pull/1619/files#diff-83c19db695b76bcbb03b8aa5675379c22d450f700bd62b34b1013151248201d0).
