### ISSUE TITLE
Is the predicate cost used during invention?

### ISSUE THREAD

**Issue by Jaraxxus-Me** [Learning-and-Intelligent-Systems/predicators#1668]
Hi, thanks for the great work.
I have a quick question regarding the grammar search predicate invention algorithm.
When running the hill_climbing search, the get_successors function [here](https://github.com/Learning-and-Intelligent-Systems/predicators/blob/b0703c873be252430baa58a4515ae2d17339adb7/predicators/approaches/grammar_search_invention_approach.py#L1006) doesn't seem to iterate the predicate candidates ranked by their cost.
In this case, where are the predicate costs used during the invention?

Thanks!

**Comment by NishanthJKumar** [comment]
Hi! Yes it is, the cost is used when considering the enumeration order of the predicates from the grammar [here](https://github.com/Learning-and-Intelligent-Systems/predicators/blob/b0703c873be252430baa58a4515ae2d17339adb7/predicators/approaches/grammar_search_invention_approach.py#L390). This influences the order predicate hypotheses will be considered in.

**Comment by NishanthJKumar** [comment]
Also note that this isn't an issue with the codebase and seems more appropriate for an email discussion, so feel free to reach out via email with follow-up questions. Closing for now.
