### ISSUE TITLE
Issue with the GNN-shooting baseline

### ISSUE THREAD

**Issue by Jaraxxus-Me** [Learning-and-Intelligent-Systems/predicators#1683]
Should the code [here](https://github.com/Learning-and-Intelligent-Systems/predicators/blob/master/predicators/approaches/gnn_option_policy_approach.py#L250) be
```
time.perf_counter() - start_time > timeout
```
If it is `<`, only the last shooting (The timed out one) will be valid, all the shootings before will only have `total_num_act=1`.
Is this intended to only allow for one-time shooting? But the timeout 10s will have no impact here.
Correct me if I'm wrong.

**Comment by NishanthJKumar** [comment]
yes - i think you're actually correct! Woops - this is probably something we should have caught earlier!

**Comment by Jaraxxus-Me** [comment]
Sure, would you please allow me to create my branch?

**Comment by Jaraxxus-Me** [comment]
PR opened!
