### ISSUE TITLE
fix grammar search invention for blocks with all ablated

### ISSUE THREAD

**Issue by tomsilver** [Learning-and-Intelligent-Systems/predicators#227]
#226 breaks grammar search invention for blocks with all ablated:

```
python src/main.py --env blocks --approach grammar_search_invention --seed 0 --excluded_predicates all
```

(we knew this at the time of merging, but we also know that the PR fixed a bug, so really we just uncovered a lurking issue)

**Comment by ronuchit** [comment]
this is a heavily outdated and pointless issue. closing
