### ISSUE TITLE
implement parallelized version of hill climbing

### ISSUE THREAD

**Issue by tomsilver** [Learning-and-Intelligent-Systems/predicators#264]
we can evaluate all successors in parallel, which will help when the heuristic evaluation is the bottleneck (which it is for predicate learning)

**Comment by ronuchit** [comment]
i can look into this but i think we might find that the overhead is too great

**Comment by ronuchit** [comment]
This looks good at a glance. Why didn't you want to make it into a PR? Couple of questions though:
1 - will it eat up the entire processor on our Macs?
2 - did you verify the scores are the same as in sequential mode?

**Comment by tomsilver** [comment]
I just didn't make a PR because I didn't have time yet to test it (so no I didn't do 2 yet). Re: 1, my computer didn't seem to slow down, but we should see.

**Comment by ronuchit** [comment]
i can take over on it later
