### ISSUE TITLE
exact lookahead is failing in cover on master

### ISSUE THREAD

**Issue by tomsilver** [Learning-and-Intelligent-Systems/predicators#272]
fyi @ronuchit . I'll investigate...

to reproduce:

```python src/main.py --env cover --approach grammar_search_invention  --seed 0 --excluded_predicates all --grammar_search_score_function exact_lookahead```

output:

```
Selected 1 predicates out of 50 candidates:
	 NOT-Forall[0:block].[((0:block).grasp<=-0.475)(0)]
Evaluating predicates: frozenset({NOT-Forall[0:block].[((0:block).grasp<=-0.475)(0)]}), with total cost 3.0
	Total score: 10.01918995852723 computed in 0.053 seconds
```

and then ultimately planning fails dramatically

**Comment by tomsilver** [comment]
```$ git bisect bad
aa525e722095eb87555b00c8bd15fc036e8b124a is the first bad commit
commit aa525e722095eb87555b00c8bd15fc036e8b124a
Author: Tom Silver <tomssilver@gmail.com>
Date:   Mon Jan 3 17:44:39 2022 -0500

    fix scaling in grammar features

 src/approaches/grammar_search_invention_approach.py | 2 +-
 ```

sigh

**Comment by tomsilver** [comment]
this is extremely strange. on master, if I make just this change:

```
$ git diff
diff --git a/src/approaches/grammar_search_invention_approach.py b/src/approaches/grammar_search_invention_approach.py
index 63dd7af..9c93fda 100644
--- a/src/approaches/grammar_search_invention_approach.py
+++ b/src/approaches/grammar_search_invention_approach.py
@@ -285,6 +285,10 @@ class _SingleFeatureInequalitiesPredicateGrammar(_DataBasedPredicateGrammar):
                         continue
                     # Scale the constant by the feature range.
                     k = constant * (ub - lb) + lb
+
+                    if "grasp" in f:
+                        k -= 1e-3
+
                     # Only need one of (ge, le) because we can use negations
                     # to get the other (modulo equality, which we shouldn't
                     # rely on anyway because of precision issues).
```

then that's the difference between learning the incorrect or correct predicates.

the difference is `NOT-((0:block).grasp<=-0.476)` vs `NOT-((0:block).grasp<=-0.475)`, for example.

what's strange is that none of the data has grasps that are anywhere close to that threshold! I verified that all grasps in the data are either -1 or greater than -0.4. so what the heck...

**Comment by tomsilver** [comment]
remarkably, this issue seems to have been resolved by #276 . I verified that reverting the sorting of the nsrts makes the difference. but I would now like to understand why...

**Comment by tomsilver** [comment]
restarting investigations now with:

```
python src/main.py --env cover --approach grammar_search_invention --seed 0 --excluded_predicates all --grammar_search_score_function exact_lookahead --task_planning_heuristic lmcut
```

which leads to the same original issue.

**Comment by tomsilver** [comment]
woah, see these proxy analysis results:

```
Evaluating predicates: frozenset(), with total cost 0
	Total score: 606.9809920803 computed in 0.020 seconds
Evaluating predicates: frozenset({HandEmpty}), with total cost 1.0
	Total score: 614.9599533210534 computed in 0.027 seconds
Evaluating predicates: frozenset({Holding}), with total cost 1.0
	Total score: 14.97497413658168 computed in 0.028 seconds
Evaluating predicates: frozenset({NOT-HandEmpty}), with total cost 1.0
	Total score: 8.019189958527264 computed in 0.027 seconds
Evaluating predicates: frozenset({HandEmpty, Holding}), with total cost 2.0
	Total score: 9.076693031965949 computed in 0.036 seconds
```

`NOT-HandEmpty` == `NOT-Forall[0:block].[((0:block).grasp<=-0.475)(0)]`, the predicate that's selected in this issue.

I was expecting that the score for this predicate alone would be better than `Holding` or `HandEmpty` individually, but still worse than them together. but it's actually better than them together...

**Comment by tomsilver** [comment]
the results seem to depend significantly on the temperature parameter that we're using in the lookahead score (`grammar_search_lookahead_based_temperature`).

- Temperature = 1.0 (**good**)
    - {NOT-HandEmpty()}: 72.46
    - {Holding, HandEmpty}: 60.76
- Temperature = 2.5 (**good**)
    - {NOT-HandEmpty()}: 22.37
    - {Holding, HandEmpty}: 19.20
- Temperature = 5.0 (**bad** but close)
    - {NOT-HandEmpty()}: 9.16
    - {Holding, HandEmpty}: 9.85
- Temperature = 10.0 (**bad**)
    - {NOT-HandEmpty()}: 8.02
    - {Holding, HandEmpty}: 9.08

**Comment by tomsilver** [comment]
I wonder if the issue is related to where the "uncertainty" occurs in the demonstrations. I need to check this, but I believe that with Not-HandEmpty, there is more uncertainty when _placing_, because you don't know which block is going to end up Cover-ing a target. but with Holding/HandEmpty, there is more uncertainty when _picking_, because you don't know whichh block is going to end up Holding after the pick. (in contrast, when picking under Not-HandEmpty, you are very confident that the result will be Not-HandEmpty, and which block it is doesn't matter.)

**Comment by ronuchit** [comment]
Why wouldn't it prefer predicates that make both placing and picking certain? (modulo whether covering works or not)

**Comment by tomsilver** [comment]
> Why wouldn't it prefer predicates that make both placing and picking certain? (modulo whether covering works or not)

well yes, but in tihs case it's impossible to be certain because there are multiple optimal plans (pick/place block1 first vs pick/place block2 first)

**Comment by tomsilver** [comment]
some more printouts...

### Not-HandEmpty

```
From state: set()
the energy-based policy is:
==================================================
Possible successor 0
Add effects: set()
Del effects: set()
On demo? False
Policy prob: 4.5397868702434354e-05
==================================================
==================================================
Possible successor 1
Add effects: {NOT-HandEmpty()}
Del effects: set()
On demo? True
Policy prob: 0.9999546021312967
==================================================
```
This much makes sense.

```
From state: {NOT-HandEmpty()}
the energy-based policy is:
==================================================
Possible successor 0
Add effects: set()
Del effects: set()
On demo? False
Policy prob: 4.539580745527396e-05
==================================================
==================================================
Possible successor 1
Add effects: {Covers(block0:block, target0:target)}
Del effects: {NOT-HandEmpty()}
On demo? True
Policy prob: 0.9999092001412235
==================================================
==================================================
Possible successor 2
Add effects: {Covers(block0:block, target1:target)}
Del effects: {NOT-HandEmpty()}
On demo? False
Policy prob: 2.0609664699807238e-09
==================================================
==================================================
Possible successor 3
Add effects: {Covers(block1:block, target0:target)}
Del effects: {NOT-HandEmpty()}
On demo? False
Policy prob: 2.0609664699807238e-09
==================================================
==================================================
Possible successor 4
Add effects: {Covers(block1:block, target1:target)}
Del effects: {NOT-HandEmpty()}
On demo? False
Policy prob: 2.0609664699807238e-09
==================================================
==================================================
Possible successor 5
Add effects: set()
Del effects: {NOT-HandEmpty()}
On demo? False
Policy prob: 2.0609664699807238e-09
==================================================
==================================================
Possible successor 6
Add effects: set()
Del effects: set()
On demo? False
Policy prob: 4.539580745527396e-05
==================================================
```
This one surprised me a little bit, because I thought there would be uncertainty. But there's actually not, because of course you would want to accomplish the goal of `Covers(block0:block, target0:target)` right away.

```
From state: {NOT-HandEmpty()}
the energy-based policy is:
==================================================
Possible successor 0
Add effects: set()
Del effects: set()
On demo? False
Policy prob: 2.2698934281041354e-05
==================================================
==================================================
Possible successor 1
Add effects: {Covers(block0:block, target0:target)}
Del effects: {NOT-HandEmpty()}
On demo? True
Policy prob: 0.499977299519923
==================================================
==================================================
Possible successor 2
Add effects: {Covers(block0:block, target1:target)}
Del effects: {NOT-HandEmpty()}
On demo? False
Policy prob: 1.030530022042537e-09
==================================================
==================================================
Possible successor 3
Add effects: {Covers(block1:block, target0:target)}
Del effects: {NOT-HandEmpty()}
On demo? False
Policy prob: 1.030530022042537e-09
==================================================
==================================================
Possible successor 4
Add effects: {Covers(block1:block, target1:target)}
Del effects: {NOT-HandEmpty()}
On demo? False
Policy prob: 0.499977299519923
==================================================
==================================================
Possible successor 5
Add effects: set()
Del effects: {NOT-HandEmpty()}
On demo? False
Policy prob: 1.030530022042537e-09
==================================================
==================================================
Possible successor 6
Add effects: set()
Del effects: set()
On demo? False
Policy prob: 2.2698934281041354e-05
==================================================
```
This is from a different demo where there are two goals, `Covers(block0:block, target0:target)` and `Covers(block1:block, target1:target)`. We can see that when holding something, there is roughly a 50/50 chance that we will accomplish each goal next, because we don't know which block is held. So this is true uncertainty.

**Comment by tomsilver** [comment]
Okay indeed they are kind of "equally good", I forgot for a while that we have other regularizing components to the score function...

After removing those, I'm seeing:

```
Evaluating predicates: frozenset({NOT-HandEmpty}), with total cost 1.0
	Total score: 6.9391899585272645 computed in 0.028 seconds
Evaluating predicates: frozenset({HandEmpty, Holding}), with total cost 2.0
	Total score: 6.936693031965949 computed in 0.059 seconds
```

So there is actually a _slight_ difference in favor of HandEmpty/Holding. I'm not sure what accounts for the difference. I thought it was a question of earlier vs later, but that doesn't seem to be the case...

Ah okay, the difference goes away when changing `unique` from `False` to `True` here, in `_evaluate_atom_trajectory`:
```
utils.get_successors_from_ground_ops(atoms, ground_ops, unique=False)
```

and my guess there is that these two operators for Not-HandEmpty can sometimes lead to the same off-demo successor states:

```
NSRT-Op0:
    Parameters: []
    Preconditions: []
    Add Effects: [NOT-HandEmpty()]
    Delete Effects: []
    Side Predicates: []
    Option Spec: PickPlace()

NSRT-Op2:
    Parameters: []
    Preconditions: []
    Add Effects: []
    Delete Effects: []
    Side Predicates: []
    Option Spec: PickPlace()
```

**Comment by tomsilver** [comment]
![exact_lookahead_bad](https://user-images.githubusercontent.com/2816502/149030040-a13da687-16d7-423d-b75f-90e2b53cefd2.png)
Figure 1 for my thesis called "exact lookahead isn't enough and life is hard"

**Comment by tomsilver** [comment]
question for discussion: would these two sets be equally good under a different planner? e.g., one that does not commit to a particular skeleton, but just uses the operators to derive a heuristic for a (continuous) state?

**Comment by tomsilver** [comment]
this was a fun deep dive, we now understand everything here
