### ISSUE TITLE
CoverMultistepOptions environment appears to find invalid solutions

### ISSUE THREAD

**Issue by czeng6** [Learning-and-Intelligent-Systems/predicators#493]
I changed the hand regions in the environment, but solutions seem to allow the robot to place outside of the changed hand regions:

https://user-images.githubusercontent.com/8839164/155862505-3d29193f-0ba6-49c3-b161-7fa18212ec18.mp4

**Comment by ronuchit** [comment]
@ashayathalye just fyi, not sure if you know about this

**Comment by tomsilver** [comment]
I think this issue was generated before we merged the most recent changes to this environment were merged, so they may have been resolved. @ashayathalye is making some changes to the environment again, but when those are complete, we'll test to see if this issue comes up.
