### ISSUE TITLE
General Improvements

### ISSUE THREAD

**Issue by williamshen-nz** [Learning-and-Intelligent-Systems/predicators#549]
- Use logging rather than print
- Add script for running all the pytest/mypy/pylint/etc. checks locally (could integrate into pre-commit but the pipeline takes a bit too long to run sometimes)
- Run isort for formatting as well
- Automatically discovering subclasses of abstract classes for different options, etc. (e.g. environments)
- Use more pytest in unit tests to reduce repeated code
- Supercloud setup script (or could be section in the Wiki)

**Comment by ronuchit** [comment]
I feel like the 5th thing (Use more pytest in unit tests to reduce repeated code) might be too annoying to be worth it in general, but we could do it for a single file just as an example. `test_structs.py` seems like the best option to me.

I like everything else a lot.

**Comment by williamshen-nz** [comment]
Yep I agree it can be annoying and there's not much point for existing tests. For new tests if there's simple ways integrate pytest (mostly fixtures and parametrizing) to make our lives easier and tests more readable then it may be worth it.

**Comment by ronuchit** [comment]
opened individual issues to make things easier to track
