### ISSUE TITLE
Consider using ClassVar and Final typing pattern

### ISSUE THREAD

**Issue by tomsilver** [Learning-and-Intelligent-Systems/predicators#624]

**Comment by ronuchit** [comment]
i thought a bit about this. according to https://stackoverflow.com/questions/66285078/how-to-define-final-classvar-variable-in-python, Final is sufficient alone on class variables. so, the proposed change here would be to wrap every class variable in our environment files into a Final[...] tag.

i feel like this is going to hurt more than help readability. it's already pretty obvious that the class variables we have are constants, and i think spamming the "Final" tag in every line will make it harder to find the constants you're looking for when scanning through the code. happy to hear other thoughts @tomsilver but my feeling is let's not make any changes here

**Comment by tomsilver** [comment]
Thanks for looking into it. That sounds reasonable to me. @williamshen-nz are there any nonobvious benefits to using them?

**Comment by williamshen-nz** [comment]
I usually just annotate with `ClassVar` as it's clearer. The benefit according to the python docs (https://docs.python.org/3/library/typing.html#typing.ClassVar) is that type checkers can use it to pick it up. In our case, mypy supposedly will do additional checks on `ClassVar` to check instances are not setting it: https://mypy.readthedocs.io/en/stable/class_basics.html

Also when you use ClassVar with dataclass then it's essentially ignored as a field which you may/may not want (docs: https://docs.python.org/3/library/dataclasses.html). So if you called `dataclasses.asdict`, `__str__`, etc. then class variables wouldn't be included in the default dataclass implementations.

I'm not familiar enough with the codebase to know how frequently class variables are being used, but if it is a lot it might cause more pain, be harder to read and require more fixing than it's worth. I'm fine either going either way

**Comment by ronuchit** [comment]
nvm i tried it and it looks alright, #639
