### ISSUE TITLE
allow `predicate_mlp_classifier_max_itr` to depend on the dataset size

### ISSUE THREAD

**Issue by tomsilver** [Learning-and-Intelligent-Systems/predicators#659]
we need this for the interactive learning approach. it will be good if we can implement this in a way that suggests a general pattern, in case we want to vary other hyperparameters later on too

**Comment by ronuchit** [comment]
is this out of date or still something we want to do?

**Comment by tomsilver** [comment]
We still may want it, but it's low priority.
