### ISSUE TITLE
investigate removing the bias terms for sampler and option learning

### ISSUE THREAD

**Issue by tomsilver** [Learning-and-Intelligent-Systems/predicators#891]
some very preliminary evidence suggests removing those terms might help, or at least be unnecessary

**Comment by ronuchit** [comment]
let's close this if the increase to `neural_gaus_regressor_max_itr` is enough?

**Comment by tomsilver** [comment]
I still think it's worth it to see whether we can get rid of it. isn't it weird?

**Comment by ronuchit** [comment]
i don't think it's weird or not weird, as long as things are working i don't care much, but if you feel strongly, we can easily run another set of supercloud experiments

**Comment by tomsilver** [comment]
yeah let's wait until things stabilize and then try it

**Comment by tomsilver** [comment]
after investigation, removing bias does not seem to help sampler learning or sampler+option learning, so we will leave this alone for now.
