### ISSUE TITLE
investigate supercloud enhancements

### ISSUE THREAD

**Issue by tomsilver** [Learning-and-Intelligent-Systems/predicators#899]
from a recent email:

> 3) Instead of submitting one job or job array task for each input or run that you have to do, you should set up your jobs so each one cycles through a subset of inputs or runs. You want to avoid having any pending jobs, especially those listed with a reason of "AssocGrpCpuLimit", as large numbers of pending jobs is mainly what slows down the scheduler. If you can reformulate your job as one big for loop that iterates through all of your inputs, the tool I usually recommend is LLsub Job Array Triples. If you cannot do this, LLMapReduce with Triples mode would be a good option. Triples submission with either of these submits one job per node, making it the most efficient way to submit these type of jobs. How to use both of these are included in the module on Submitting Jobs in the Practical HPC Course (https://learn.llx.edly.io/course/practical-hpc/), and in the resources below:
>  
> 
> - LLsub Job Array Triples: https://supercloud.mit.edu/job-arrays-llsub-triples-3-steps
> 
> - LLMapReduce: Tutorial and examples in /home/gridsan/groups/bwedx/Practical_HPC_2022/LLMapReduce

**Comment by ronuchit** [comment]
oops, forgot to close this. closed by #921
