### ISSUE TITLE
add support for hierarchical types

### ISSUE THREAD

**Issue by tomsilver** [Learning-and-Intelligent-Systems/predicators#94]
This would be useful not only in the behavior integration, but also in @amburger66 's work, so I would like to prioritize it. I think it should be the next chunky thing that I work on. @ronuchit lmk what you think

**Comment by ronuchit** [comment]
No problem with me. I won't have much time to work on coding stuff for the next 1.5 weeks, but it would be good to sync up on the design before you start implementing.

**Comment by ronuchit** [comment]
@tomsilver can we close this?

**Comment by ronuchit** [comment]
See https://github.com/Learning-and-Intelligent-Systems/predicators/pull/95

**Comment by tomsilver** [comment]
Yeah we can close it, but for posterity, note that we still need to change the operator learning code to handle hierarchical types. Simplest algorithm would be to try to collapse overly type-specific operators posthoc.
