### ISSUE TITLE
temporarily save training tasks during data generation

### ISSUE THREAD

**Issue by ronuchit** [Learning-and-Intelligent-Systems/predicators#946]
To prevent a crash from ruining all our data collection so far, we can modify `demo_only.py` to temporarily save each demonstration as it's looping through the training tasks. At the end, we should delete all these temporary files.

On any run of the system, if one of these temporary files exists for a particular training task, we should _always_ load it. (Regardless of any setting of `--load_data` or whatever else.)

**Comment by tomsilver** [comment]
Another thing we should try to address in this issue is that if we have already collected 100 demos, but we want to test with 50, we should not need to collect a new dataset. This maybe indicates we should be saving data per task.

**Comment by ronuchit** [comment]
We need to be particularly careful with this whole thing because in the current system, there is a lot of overwriting of the files in `saved_datasets` going on when we do supercloud runs. It's been okay thus far because we only write the data out once at the end of data collection, but we don't want processes to conflict if we're saving individual demonstrations.

**Comment by ronuchit** [comment]
> Another thing we should try to address in this issue is that if we have already collected 100 demos, but we want to experiment with 50, we should not need to collect a new dataset. This maybe indicates we should be saving data per task.

Perhaps. Although I'm worried that there will be an annoyingly large number of files in `saved_datasets` then. This could also be addressed a different way, by just searching for dataset filenames that have >= the required amount of data.

As before, we need to think about whether things would go well on supercloud.
