### ISSUE TITLE
Make the effect of collisions consistent between Cover and Stick-button. 

### ISSUE THREAD

**Issue by ashayathalye** [Learning-and-Intelligent-Systems/predicators#950]
In Stick-button, a collision causes an EnvironmentFailure exception, while in Cover, a collision causes the action that caused the collision to be replaced by a NOOP, such that the state does not change.

I wonder if this has implications on learning. During planning, NOOPs are detected automatically and the simulation is stopped. But does this happen when testing? 

Might as well fix for consistency.

**Comment by ronuchit** [comment]
the general idea of using a no-op action when a collision would occur is pervasive in the code, spanning not just cover but nearly all of our environments. so we shouldn't try to get rid of it.

from a planning perspective, a no-op is identical to an EnvironmentFailure when we use `sesame_propagate_failures = "never"` which is True for stick_button (https://github.com/Learning-and-Intelligent-Systems/predicators/blob/master/src/settings.py#L404)

i don't know about learning but maybe @tomsilver has some insights. what would go wrong if we replaced the stick_button EnvironmentFailure with a no-op?
